export const seckill = data => request.post('/seckill', data)
export const querySeckillResult = requestId =>
  request.get('/seckill/result', { params: { requestId } })
export const paySeckillOrder = orderId => request.post(`/seckill/order/${orderId}/pay`)
export const cancelSeckillOrder = orderId => request.post(`/seckill/order/${orderId}/cancel`)
export const getMySeckillOrders = () => request.get('/seckill/order/my')
export const getCurrentActivity = () => request.get('/seckill/activity/current')
export const getActivityList = () => request.get('/seckill/activity/list')
export const getSeckillStock = params => request.get('/seckill/stock', { params })
export const initActivityStock = activityId => request.post(`/seckill/admin/init/${activityId}`)
export const resetActivity = activityId => request.post(`/seckill/admin/reset/${activityId}`)
export const rebuildActivity = params => request.post('/seckill/admin/rebuild', null, { params })
export const consumeOrders = batchSize => request.post('/seckill/admin/consume', null, { params: { batchSize } })
export const reconcileSeckill = activityId => request.get('/seckill/admin/reconcile', { params: { activityId } })
export const compensateSeckill = params => request.post('/seckill/admin/compensate', null, { params })
